version: '3'
services:
  mc:
    image: itzg/minecraft-server
    environment:
      - EULA=true
      - VERSION=1.20
      - WORLD=world2
    ports:
      - "25565:25565"
    volumes:
      - ./world:/worlds/world/
