version: '3'
services:
  mc:
    image: itzg/minecraft-server
    environment:
      - EULA=true
      - VERSION=1.20
      - WORLD=https://www.curseforge.com/api/v1/mods/644465/files/5385444/download
    ports:
      - "25565:25565"
    volumes:
      - ./world:/worlds/world/
